In [26]:
import requests

url = "https://api.openalex.org/works"

params = {
    "search": "machine learning",
    "filter": "from_publication_date:2018-01-01,has_abstract:true,type:article",
    "per-page": 20
}

response = requests.get(url, params=params)

print(response.status_code)

200

In [2]:
data = response.json()

data.keys()

dict_keys(['meta', 'results', 'group_by'])

In [3]:
paper = data["results"][0]

paper.keys()

dict_keys(['id', 'doi', 'title', 'display_name', 'relevance_score', 'publication_year', 'publication_date', 'ids', 'language', 'primary_location', 'type', 'indexed_in', 'open_access', 'authorships', 'institutions', 'countries_distinct_count', 'institutions_distinct_count', 'corresponding_author_ids', 'corresponding_institution_ids', 'apc_list', 'apc_paid', 'fwci', 'has_fulltext', 'cited_by_count', 'citation_normalized_percentile', 'cited_by_percentile_year', 'biblio', 'is_retracted', 'is_paratext', 'is_xpac', 'primary_topic', 'topics', 'keywords', 'concepts', 'mesh', 'locations_count', 'locations', 'best_oa_location', 'sustainable_development_goals', 'awards', 'funders', 'has_content', 'content_urls', 'referenced_works_count', 'referenced_works', 'related_works', 'abstract_inverted_index', 'counts_by_year', 'updated_date', 'created_date'])

In [4]:
print("TITLE:")
print(paper["title"])

print("\nYEAR:")
print(paper["publication_year"])

print("\nCITATIONS:")
print(paper["cited_by_count"])

TITLE:
Artificial intelligence: a modern approach

YEAR:
1995

CITATIONS:
22260

In [5]:
print("\nAUTHORS:")
print(paper["authorships"][:2])

AUTHORS:
[{'author_position': 'first', 'author': {'id': None, 'display_name': 'Dr. Anil Kumar', 'orcid': None}, 'institutions': [{'id': 'https://openalex.org/I95457486', 'display_name': 'University of California, Berkeley', 'ror': 'https://ror.org/01an7q238', 'country_code': 'US', 'type': 'education', 'lineage': ['https://openalex.org/I95457486']}], 'countries': ['US'], 'is_corresponding': False, 'raw_author_name': 'Dr. Anil Kumar', 'raw_affiliation_strings': ['University of California, Berkeley'], 'raw_orcid': None, 'affiliations': [{'raw_affiliation_string': 'University of California, Berkeley', 'institution_ids': ['https://openalex.org/I95457486']}]}, {'author_position': 'middle', 'author': {'id': None, 'display_name': 'Sivasubramanian Balasubramanian', 'orcid': None}, 'institutions': [{'id': 'https://openalex.org/I1174212', 'display_name': 'University of Southern California', 'ror': 'https://ror.org/03taz7m60', 'country_code': 'US', 'type': 'education', 'lineage': ['https://openalex.org/I1174212']}, {'id': 'https://openalex.org/I95457486', 'display_name': 'University of California, Berkeley', 'ror': 'https://ror.org/01an7q238', 'country_code': 'US', 'type': 'education', 'lineage': ['https://openalex.org/I95457486']}], 'countries': ['US'], 'is_corresponding': False, 'raw_author_name': 'Sivasubramanian Balasubramanian', 'raw_affiliation_strings': ['Univ. of Southern California, Los Angeles; Univ. of California, Berkeley; and Sun Microsystems Labs.#TAB#'], 'raw_orcid': None, 'affiliations': [{'raw_affiliation_string': 'Univ. of Southern California, Los Angeles; Univ. of California, Berkeley; and Sun Microsystems Labs.#TAB#', 'institution_ids': ['https://openalex.org/I1174212', 'https://openalex.org/I95457486']}]}]

In [6]:
print("\nABSTRACT:")
print(paper["abstract_inverted_index"])

ABSTRACT:
{'The': [0], 'long-anticipated': [1], 'revision': [2], 'of': [3, 13, 22], 'this': [4], '#1': [5], 'selling': [6], 'book': [7], 'offers': [8], 'the': [9, 14, 18], 'most': [10], 'comprehensive,': [11], 'state': [12], 'art': [15], 'introduction': [16], 'to': [17], 'theory': [19], 'and': [20, 59, 96], 'practice': [21], 'artificial': [23, 101], 'intelligence': [24], 'for': [25], 'modern': [26], 'applications.': [27], 'Intelligent': [28], 'Agents.': [29], 'Solving': [30], 'Problems': [31], 'by': [32], 'Searching.': [33], 'Informed': [34], 'Search': [35], 'Methods.': [36], 'Game': [37], 'Playing.': [38], 'Agents': [39, 83], 'that': [40, 84], 'Reason': [41], 'Logically.': [42], 'First-order': [43], 'Logic.': [44, 52], 'Building': [45], 'a': [46], 'Knowledge': [47, 80], 'Base.': [48], 'Inference': [49], 'in': [50, 81, 88, 100], 'First-Order': [51], 'Logical': [53], 'Reasoning': [54, 63], 'Systems.': [55, 64], 'Practical': [56, 86], 'Planning.': [57], 'Planning': [58], 'Acting.': [60], 'Uncertainty.': [61], 'Probabilistic': [62], 'Making': [65, 68], 'Simple': [66], 'Decisions.': [67, 70], 'Complex': [69], 'Learning': [71, 74], 'from': [72], 'Observations.': [73], 'with': [75], 'Neural': [76], 'Networks.': [77], 'Reinforcement': [78], 'Learning.': [79, 82], 'Communicate.': [85], 'Communication': [87], 'English.': [89], 'Perception.': [90], 'Robotics.': [91], 'For': [92], 'computer': [93], 'professionals,': [94], 'linguists,': [95], 'cognitive': [97], 'scientists': [98], 'interested': [99], 'intelligence.': [102]}

In [7]:
len(data["results"])

10

In [8]:
import pandas as pd

papers = pd.DataFrame(data["results"])

papers.shape

(10, 50)

In [9]:
papers[
    [
        "id",
        "title",
        "publication_year",
        "cited_by_count"
    ]
]

,id,title,publication_year,cited_by_count
0,https://openalex.org/W2122410182,Artificial intelligence: a modern approach,1995,22260
1,https://openalex.org/W2623293810,Artificial intelligence: A modern approach,1996,10702
2,https://openalex.org/W2908201961,High-performance medicine: the convergence of ...,2018,9784
3,https://openalex.org/W26772505,Lecture Notes in Artificial Intelligence,1999,7440
4,https://openalex.org/W2981731882,Explainable Artificial Intelligence (XAI): Con...,2019,9753
5,https://openalex.org/W2803760365,Artificial intelligence in radiology,2018,3758
6,https://openalex.org/W3017131514,Artificial Intelligence in Education: A Review,2020,3868
7,https://openalex.org/W2664267452,"Artificial intelligence in healthcare: past, p...",2017,4835
8,https://openalex.org/W2152475379,Principles of Artificial Intelligence,1982,3357
9,https://openalex.org/W2953532875,The potential for artificial intelligence in h...,2019,3811

In [10]:
paper.keys()

dict_keys(['id', 'doi', 'title', 'display_name', 'relevance_score', 'publication_year', 'publication_date', 'ids', 'language', 'primary_location', 'type', 'indexed_in', 'open_access', 'authorships', 'institutions', 'countries_distinct_count', 'institutions_distinct_count', 'corresponding_author_ids', 'corresponding_institution_ids', 'apc_list', 'apc_paid', 'fwci', 'has_fulltext', 'cited_by_count', 'citation_normalized_percentile', 'cited_by_percentile_year', 'biblio', 'is_retracted', 'is_paratext', 'is_xpac', 'primary_topic', 'topics', 'keywords', 'concepts', 'mesh', 'locations_count', 'locations', 'best_oa_location', 'sustainable_development_goals', 'awards', 'funders', 'has_content', 'content_urls', 'referenced_works_count', 'referenced_works', 'related_works', 'abstract_inverted_index', 'counts_by_year', 'updated_date', 'created_date'])

In [11]:
papers.shape

(10, 50)

In [12]:
papers[["title", "publication_year", "cited_by_count"]]

,title,publication_year,cited_by_count
0,Artificial intelligence: a modern approach,1995,22260
1,Artificial intelligence: A modern approach,1996,10702
2,High-performance medicine: the convergence of ...,2018,9784
3,Lecture Notes in Artificial Intelligence,1999,7440
4,Explainable Artificial Intelligence (XAI): Con...,2019,9753
5,Artificial intelligence in radiology,2018,3758
6,Artificial Intelligence in Education: A Review,2020,3868
7,"Artificial intelligence in healthcare: past, p...",2017,4835
8,Principles of Artificial Intelligence,1982,3357
9,The potential for artificial intelligence in h...,2019,3811

In [13]:
papers.isnull().sum()

id                                0
doi                               1
title                             0
display_name                      0
relevance_score                   0
publication_year                  0
publication_date                  0
ids                               0
language                          0
primary_location                  0
type                              0
indexed_in                        0
open_access                       0
authorships                       0
institutions                      0
countries_distinct_count          0
institutions_distinct_count       0
corresponding_author_ids          0
corresponding_institution_ids     0
apc_list                          4
apc_paid                          7
fwci                              1
has_fulltext                      0
cited_by_count                    0
citation_normalized_percentile    1
cited_by_percentile_year          1
biblio                            0
is_retracted                      0
is_paratext                       0
is_xpac                           0
primary_topic                     0
topics                            0
keywords                          0
concepts                          0
mesh                              0
locations_count                   0
locations                         0
best_oa_location                  4
sustainable_development_goals     0
awards                            0
funders                           0
has_content                       0
content_urls                      7
referenced_works_count            0
referenced_works                  0
related_works                     0
abstract_inverted_index           6
counts_by_year                    0
updated_date                      0
created_date                      0
dtype: int64

In [14]:
papers["publication_year"].value_counts().sort_index()

publication_year
1982    1
1995    1
1996    1
1999    1
2017    1
2018    2
2019    2
2020    1
Name: count, dtype: int64

In [15]:
papers["abstract_inverted_index"].isnull().sum()

np.int64(6)

In [16]:
paper["abstract_inverted_index"]

{'The': [0],
 'long-anticipated': [1],
 'revision': [2],
 'of': [3, 13, 22],
 'this': [4],
 '#1': [5],
 'selling': [6],
 'book': [7],
 'offers': [8],
 'the': [9, 14, 18],
 'most': [10],
 'comprehensive,': [11],
 'state': [12],
 'art': [15],
 'introduction': [16],
 'to': [17],
 'theory': [19],
 'and': [20, 59, 96],
 'practice': [21],
 'artificial': [23, 101],
 'intelligence': [24],
 'for': [25],
 'modern': [26],
 'applications.': [27],
 'Intelligent': [28],
 'Agents.': [29],
 'Solving': [30],
 'Problems': [31],
 'by': [32],
 'Searching.': [33],
 'Informed': [34],
 'Search': [35],
 'Methods.': [36],
 'Game': [37],
 'Playing.': [38],
 'Agents': [39, 83],
 'that': [40, 84],
 'Reason': [41],
 'Logically.': [42],
 'First-order': [43],
 'Logic.': [44, 52],
 'Building': [45],
 'a': [46],
 'Knowledge': [47, 80],
 'Base.': [48],
 'Inference': [49],
 'in': [50, 81, 88, 100],
 'First-Order': [51],
 'Logical': [53],
 'Reasoning': [54, 63],
 'Systems.': [55, 64],
 'Practical': [56, 86],
 'Planning.': [57],
 'Planning': [58],
 'Acting.': [60],
 'Uncertainty.': [61],
 'Probabilistic': [62],
 'Making': [65, 68],
 'Simple': [66],
 'Decisions.': [67, 70],
 'Complex': [69],
 'Learning': [71, 74],
 'from': [72],
 'Observations.': [73],
 'with': [75],
 'Neural': [76],
 'Networks.': [77],
 'Reinforcement': [78],
 'Learning.': [79, 82],
 'Communicate.': [85],
 'Communication': [87],
 'English.': [89],
 'Perception.': [90],
 'Robotics.': [91],
 'For': [92],
 'computer': [93],
 'professionals,': [94],
 'linguists,': [95],
 'cognitive': [97],
 'scientists': [98],
 'interested': [99],
 'intelligence.': [102]}

In [17]:
def reconstruct_abstract(inverted_index):
    if inverted_index is None:
        return None

    words = []

    for word, positions in inverted_index.items():
        for position in positions:
            words.append((position, word))

    words.sort()

    return " ".join(word for position, word in words)

In [18]:
abstract = reconstruct_abstract(paper["abstract_inverted_index"])

print(abstract)

The long-anticipated revision of this #1 selling book offers the most comprehensive, state of the art introduction to the theory and practice of artificial intelligence for modern applications. Intelligent Agents. Solving Problems by Searching. Informed Search Methods. Game Playing. Agents that Reason Logically. First-order Logic. Building a Knowledge Base. Inference in First-Order Logic. Logical Reasoning Systems. Practical Planning. Planning and Acting. Uncertainty. Probabilistic Reasoning Systems. Making Simple Decisions. Making Complex Decisions. Learning from Observations. Learning with Neural Networks. Reinforcement Learning. Knowledge in Learning. Agents that Communicate. Practical Communication in English. Perception. Robotics. For computer professionals, linguists, and cognitive scientists interested in artificial intelligence.

In [19]:
print("Title:")
print(paper["title"])

print("\nAbstract:")
print(abstract)

Title:
Artificial intelligence: a modern approach

Abstract:
The long-anticipated revision of this #1 selling book offers the most comprehensive, state of the art introduction to the theory and practice of artificial intelligence for modern applications. Intelligent Agents. Solving Problems by Searching. Informed Search Methods. Game Playing. Agents that Reason Logically. First-order Logic. Building a Knowledge Base. Inference in First-Order Logic. Logical Reasoning Systems. Practical Planning. Planning and Acting. Uncertainty. Probabilistic Reasoning Systems. Making Simple Decisions. Making Complex Decisions. Learning from Observations. Learning with Neural Networks. Reinforcement Learning. Knowledge in Learning. Agents that Communicate. Practical Communication in English. Perception. Robotics. For computer professionals, linguists, and cognitive scientists interested in artificial intelligence.

In [20]:
papers["abstract"] = papers["abstract_inverted_index"].apply(
    reconstruct_abstract
)

In [22]:
papers[["title", "abstract"]].head(10)

,title,abstract
0,Artificial intelligence: a modern approach,The long-anticipated revision of this #1 selli...
1,Artificial intelligence: A modern approach,None
2,High-performance medicine: the convergence of ...,None
3,Lecture Notes in Artificial Intelligence,None
4,Explainable Artificial Intelligence (XAI): Con...,None
5,Artificial intelligence in radiology,None
6,Artificial Intelligence in Education: A Review,The purpose of this study was to assess the im...
7,"Artificial intelligence in healthcare: past, p...",Artificial intelligence (AI) aims to mimic hum...
8,Principles of Artificial Intelligence,None
9,The potential for artificial intelligence in h...,The complexity and rise of data in healthcare ...

In [23]:
papers["abstract"].notna().sum()

np.int64(4)

In [24]:
papers[[
    "title",
    "publication_year",
    "topics",
    "keywords",
    "cited_by_count"
]].head(3)

,title,publication_year,topics,keywords,cited_by_count
0,Artificial intelligence: a modern approach,1995,"[{'id': 'https://openalex.org/T13062', 'displa...",[{'id': 'https://openalex.org/keywords/artific...,22260
1,Artificial intelligence: A modern approach,1996,"[{'id': 'https://openalex.org/T10126', 'displa...",[{'id': 'https://openalex.org/keywords/compute...,10702
2,High-performance medicine: the convergence of ...,2018,"[{'id': 'https://openalex.org/T11636', 'displa...",[{'id': 'https://openalex.org/keywords/workflo...,9784

In [25]:
papers[[
    "title",
    "publication_year",
    "topics",
    "keywords",
    "cited_by_count"
]].dtypes

title               object
publication_year     int64
topics              object
keywords            object
cited_by_count       int64
dtype: object

In [27]:
data = response.json()

papers = pd.DataFrame(data["results"])

print(papers.shape)

(20, 50)

In [28]:
papers[[
    "title",
    "publication_year",
    "type",
    "has_fulltext",
    "cited_by_count"
]]

,title,publication_year,type,has_fulltext,cited_by_count
0,Federated Machine Learning,2019,article,False,6218
1,Machine Learning in Medicine,2019,article,False,4373
2,Multimodal Machine Learning: A Survey and Taxo...,2018,article,False,4649
3,Machine Learning in Agriculture: A Review,2018,article,True,3272
4,Machine learning and deep learning,2021,article,True,2603
5,Machine Learning for Fluid Mechanics,2019,article,True,2790
6,Machine Learning Algorithms - A Review,2020,article,False,2507
7,Machine learning and the physical sciences,2019,article,False,2501
8,Explainable AI: A Review of Machine Learning I...,2020,article,False,2898
9,Empirical Asset Pricing via Machine Learning,2020,article,True,2434
10,"Definitions, methods, and applications in inte...",2019,article,True,2157
11,Recent advances and applications of machine le...,2019,article,True,2512
12,Machine Learning Interpretability: A Survey on...,2019,article,True,1820
13,All-optical machine learning using diffractive...,2018,article,False,2548
14,Machine Learning Identifies Stemness Features ...,2018,article,False,2384
15,Quantum Machine Learning in Feature Hilbert Sp...,2019,article,False,1796
16,Implementation of machine-learning classificat...,2018,article,False,2031
17,TRIPOD+AI statement: updated guidance for repo...,2024,article,True,3105
18,Techniques for interpretable machine learning,2019,article,False,1268
19,Machine learning algorithm validation with a l...,2019,article,True,1805

In [29]:
papers.shape

(20, 50)

In [30]:
papers["abstract_inverted_index"].notna().sum()

np.int64(20)

In [31]:
papers[["title", "topics"]].head(3)

,title,topics
0,Federated Machine Learning,"[{'id': 'https://openalex.org/T10764', 'displa..."
1,Machine Learning in Medicine,"[{'id': 'https://openalex.org/T13702', 'displa..."
2,Multimodal Machine Learning: A Survey and Taxo...,"[{'id': 'https://openalex.org/T11309', 'displa..."

In [32]:
papers["abstract_inverted_index"].notna().sum()

np.int64(20)

In [33]:
papers[["title", "topics"]].head(3)

,title,topics
0,Federated Machine Learning,"[{'id': 'https://openalex.org/T10764', 'displa..."
1,Machine Learning in Medicine,"[{'id': 'https://openalex.org/T13702', 'displa..."
2,Multimodal Machine Learning: A Survey and Taxo...,"[{'id': 'https://openalex.org/T11309', 'displa..."

In [34]:
papers.iloc[0]["topics"]

[{'id': 'https://openalex.org/T10764',
  'display_name': 'Privacy-Preserving Technologies in Data',
  'score': 1.0,
  'subfield': {'id': 'https://openalex.org/subfields/1702',
   'display_name': 'Artificial Intelligence'},
  'field': {'id': 'https://openalex.org/fields/17',
   'display_name': 'Computer Science'},
  'domain': {'id': 'https://openalex.org/domains/3',
   'display_name': 'Physical Sciences'}},
 {'id': 'https://openalex.org/T10237',
  'display_name': 'Cryptography and Data Security',
  'score': 0.9973000288009644,
  'subfield': {'id': 'https://openalex.org/subfields/1702',
   'display_name': 'Artificial Intelligence'},
  'field': {'id': 'https://openalex.org/fields/17',
   'display_name': 'Computer Science'},
  'domain': {'id': 'https://openalex.org/domains/3',
   'display_name': 'Physical Sciences'}},
 {'id': 'https://openalex.org/T11598',
  'display_name': 'Internet Traffic Analysis and Secure E-voting',
  'score': 0.9965000152587891,
  'subfield': {'id': 'https://openalex.org/subfields/1702',
   'display_name': 'Artificial Intelligence'},
  'field': {'id': 'https://openalex.org/fields/17',
   'display_name': 'Computer Science'},
  'domain': {'id': 'https://openalex.org/domains/3',
   'display_name': 'Physical Sciences'}}]

In [35]:
for i in range(5):
    print(f"\nPAPER {i}: {papers.iloc[i]['title']}")
    for topic in papers.iloc[i]["topics"]:
        print("  -", topic["display_name"], "| score:", topic["score"])

PAPER 0: Federated Machine Learning
  - Privacy-Preserving Technologies in Data | score: 1.0
  - Cryptography and Data Security | score: 0.9973000288009644
  - Internet Traffic Analysis and Secure E-voting | score: 0.9965000152587891

PAPER 1: Machine Learning in Medicine
  - Machine Learning in Healthcare | score: 0.998199999332428
  - Artificial Intelligence in Healthcare and Education | score: 0.9979000091552734
  - Electronic Health Records Systems | score: 0.9948999881744385

PAPER 2: Multimodal Machine Learning: A Survey and Taxonomy
  - Music and Audio Processing | score: 0.9983000159263611
  - Advanced Text Analysis Techniques | score: 0.9890000224113464
  - Advanced Chemical Sensor Technologies | score: 0.9860000014305115

PAPER 3: Machine Learning in Agriculture: A Review
  - Smart Agriculture and AI | score: 0.9998000264167786
  - Spectroscopy and Chemometric Analyses | score: 0.9825999736785889
  - Remote Sensing in Agriculture | score: 0.958299994468689

PAPER 4: Machine learning and deep learning
  - Big Data and Digital Economy | score: 0.0794999971985817
  - Knowledge Management and Technology | score: 0.03700000047683716
  - Big Data and Business Intelligence | score: 0.03220000118017197

In [36]:
params = {
    "search": "natural language processing",
    "filter": "from_publication_date:2018-01-01,has_abstract:true,type:article",
    "per-page": 20
}

response = requests.get(
    "https://api.openalex.org/works",
    params=params
)

data = response.json()
nlp_papers = pd.DataFrame(data["results"])

print(nlp_papers.shape)

(20, 50)

In [37]:
nlp_papers[[
    "title",
    "publication_year",
    "type",
    "cited_by_count"
]]

,title,publication_year,type,cited_by_count
0,"Pre-train, Prompt, and Predict: A Systematic S...",2022,article,3825
1,Recent Trends in Deep Learning Based Natural L...,2018,article,2907
2,Domain-Specific Language Model Pretraining for...,2021,article,2144
3,Recent Advances in Natural Language Processing...,2023,article,1264
4,Attention in Natural Language Processing,2020,article,638
5,Data Statements for Natural Language Processin...,2018,article,844
6,Natural language processing (NLP) in managemen...,2020,article,536
7,Natural Language Processing of Social Media as...,2018,article,528
8,Deep learning in clinical natural language pro...,2019,article,509
9,Natural Language Processing for Requirements E...,2021,article,313
10,Adversarial Attacks on Deep-learning Models in...,2020,article,422
11,Data augmentation approaches in natural langua...,2022,article,343
12,A comparison of word embeddings for the biomed...,2018,article,388
13,Five sources of bias in natural language proce...,2021,article,293
14,Brains and algorithms partially converge in na...,2022,article,331
15,Graph Neural Networks for Natural Language Pro...,2023,article,281
16,Clinical Natural Language Processing in langua...,2018,article,313
17,Natural Language Processing for Smart Healthcare,2022,article,222
18,Data-driven materials research enabled by natu...,2020,article,307
19,BERT applications in natural language processi...,2025,article,224

In [38]:
nlp_papers["abstract_inverted_index"].notna().sum()

np.int64(20)

In [28]:
import requests
import pandas as pd
import time

def collect_openalex_papers(
    search_term,
    start_year=2018,
    end_year=2026,
    max_papers=1000,
    per_page=100
):
    
    url = "https://api.openalex.org/works"
    
    all_papers = []
    cursor = "*"
    
    while len(all_papers) < max_papers:
        
        params = {
            "search": search_term,
            "filter": (
                f"from_publication_date:{start_year}-01-01,"
                f"to_publication_date:{end_year}-12-31,"
                "has_abstract:true,"
                "type:article"
            ),
            "per-page": per_page,
            "cursor": cursor
        }
        
        response = requests.get(url, params=params)
        
        if response.status_code != 200:
            raise Exception(
                f"API request failed: {response.status_code}"
            )
        
        data = response.json()
        
        results = data["results"]
        
        if not results:
            break
        
        all_papers.extend(results)
        
        cursor = data["meta"]["next_cursor"]
        
        print(f"Collected {len(all_papers)} papers...")
        
        time.sleep(0.1)
    
    papers = pd.DataFrame(all_papers)
    
    return papers.head(max_papers)

In [40]:
ml_papers = collect_openalex_papers("machine learning")

print(ml_papers.shape)

(100, 50)

In [41]:
nlp_papers = collect_openalex_papers(
    "natural language processing"
)

print(nlp_papers.shape)

(100, 50)

In [42]:
ml_papers[[
    "title",
    "publication_year",
    "type",
    "cited_by_count"
]].head(10)

,title,publication_year,type,cited_by_count
0,Federated Machine Learning,2019,article,6218
1,Machine Learning in Medicine,2019,article,4373
2,Multimodal Machine Learning: A Survey and Taxo...,2018,article,4649
3,Machine Learning in Agriculture: A Review,2018,article,3272
4,Machine learning and deep learning,2021,article,2603
5,Machine Learning for Fluid Mechanics,2019,article,2790
6,Machine Learning Algorithms - A Review,2020,article,2507
7,Machine learning and the physical sciences,2019,article,2501
8,Explainable AI: A Review of Machine Learning I...,2020,article,2898
9,Empirical Asset Pricing via Machine Learning,2020,article,2434

In [43]:
nlp_papers[[
    "title",
    "publication_year",
    "type",
    "cited_by_count"
]].head(10)

,title,publication_year,type,cited_by_count
0,"Pre-train, Prompt, and Predict: A Systematic S...",2022,article,3825
1,Recent Trends in Deep Learning Based Natural L...,2018,article,2907
2,Domain-Specific Language Model Pretraining for...,2021,article,2144
3,Recent Advances in Natural Language Processing...,2023,article,1264
4,Attention in Natural Language Processing,2020,article,638
5,Data Statements for Natural Language Processin...,2018,article,844
6,Natural language processing (NLP) in managemen...,2020,article,536
7,Natural Language Processing of Social Media as...,2018,article,528
8,Deep learning in clinical natural language pro...,2019,article,509
9,Natural Language Processing for Requirements E...,2021,article,313

In [45]:
test_papers = collect_openalex_papers(
    "natural language processing",
    max_papers=250
)

Collected 100 papers...
Collected 200 papers...
Collected 300 papers...

In [46]:
test_papers["abstract_inverted_index"].notna().sum()

np.int64(250)

In [47]:
test_papers["publication_year"].value_counts().sort_index()

publication_year
2018    28
2019    28
2020    43
2021    47
2022    48
2023    28
2024    23
2025     5
Name: count, dtype: int64

In [48]:
test_papers[[
    "title",
    "publication_year",
    "cited_by_count"
]].head(20)

,title,publication_year,cited_by_count
0,"Pre-train, Prompt, and Predict: A Systematic S...",2022,3825
1,Recent Trends in Deep Learning Based Natural L...,2018,2907
2,Domain-Specific Language Model Pretraining for...,2021,2144
3,Recent Advances in Natural Language Processing...,2023,1264
4,Attention in Natural Language Processing,2020,638
5,Data Statements for Natural Language Processin...,2018,844
6,Natural language processing (NLP) in managemen...,2020,536
7,Natural Language Processing of Social Media as...,2018,528
8,Deep learning in clinical natural language pro...,2019,509
9,Natural Language Processing for Requirements E...,2021,313
10,Adversarial Attacks on Deep-learning Models in...,2020,422
11,Data augmentation approaches in natural langua...,2022,343
12,A comparison of word embeddings for the biomed...,2018,388
13,Five sources of bias in natural language proce...,2021,293
14,Brains and algorithms partially converge in na...,2022,331
15,Graph Neural Networks for Natural Language Pro...,2023,281
16,Clinical Natural Language Processing in langua...,2018,313
17,Natural Language Processing for Smart Healthcare,2022,222
18,Data-driven materials research enabled by natu...,2020,307
19,BERT applications in natural language processi...,2025,224

In [49]:
test_papers.shape

(250, 50)

In [29]:
research_areas = [
    "machine learning",
    "deep learning",
    "natural language processing",
    "computer vision",
    "large language models",
    "reinforcement learning",
    "explainable artificial intelligence"
]

all_papers = []

for area in research_areas:
    print(f"\nCollecting: {area}")
    
    area_papers = collect_openalex_papers(
        area,
        start_year=2018,
        end_year=2026,
        max_papers=1500
    )
    
    area_papers["search_area"] = area
    
    all_papers.append(area_papers)

Collecting: machine learning
Collected 100 papers...
Collected 200 papers...
Collected 300 papers...
Collected 400 papers...
Collected 500 papers...
Collected 600 papers...
Collected 700 papers...
Collected 800 papers...
Collected 900 papers...
Collected 1000 papers...
Collected 1100 papers...
Collected 1200 papers...
Collected 1300 papers...
Collected 1400 papers...
Collected 1500 papers...

Collecting: deep learning
Collected 100 papers...
Collected 200 papers...
Collected 300 papers...
Collected 400 papers...
Collected 500 papers...
Collected 600 papers...
Collected 700 papers...
Collected 800 papers...
Collected 900 papers...
Collected 1000 papers...
Collected 1100 papers...
Collected 1200 papers...
Collected 1300 papers...
Collected 1400 papers...
Collected 1500 papers...

Collecting: natural language processing
Collected 100 papers...
Collected 200 papers...
Collected 300 papers...
Collected 400 papers...
Collected 500 papers...
Collected 600 papers...
Collected 700 papers...
Collected 800 papers...
Collected 900 papers...
Collected 1000 papers...
Collected 1100 papers...
Collected 1200 papers...
Collected 1300 papers...
Collected 1400 papers...
Collected 1500 papers...

Collecting: computer vision
Collected 100 papers...
Collected 200 papers...
Collected 300 papers...
Collected 400 papers...
Collected 500 papers...
Collected 600 papers...
Collected 700 papers...
Collected 800 papers...
Collected 900 papers...
Collected 1000 papers...
Collected 1100 papers...
Collected 1200 papers...
Collected 1300 papers...
Collected 1400 papers...
Collected 1500 papers...

Collecting: large language models
Collected 100 papers...
Collected 200 papers...
Collected 300 papers...
Collected 400 papers...
Collected 500 papers...
Collected 600 papers...
Collected 700 papers...
Collected 800 papers...
Collected 900 papers...
Collected 1000 papers...
Collected 1100 papers...

Exception: API request failed: 429

In [52]:
combined_papers = pd.concat(
    all_papers,
    ignore_index=True
)

print(combined_papers.shape)

(1750, 51)

In [53]:
print("Total records:", len(combined_papers))
print("Unique papers:", combined_papers["id"].nunique())
print(
    "Duplicate records:",
    len(combined_papers) - combined_papers["id"].nunique()
)

Total records: 1750
Unique papers: 1713
Duplicate records: 37

In [54]:
duplicate_papers = combined_papers[
    combined_papers["id"].duplicated(keep=False)
].sort_values("id")

duplicate_papers[[
    "id",
    "title",
    "search_area"
]]

,id,title,search_area
331,https://openalex.org/W2768956845,Applications of Deep Learning and Reinforcemen...,deep learning
1261,https://openalex.org/W2768956845,Applications of Deep Learning and Reinforcemen...,reinforcement learning
254,https://openalex.org/W2794284562,Deep Learning for Computer Vision: A Brief Review,deep learning
750,https://openalex.org/W2794284562,Deep Learning for Computer Vision: A Brief Review,computer vision
13,https://openalex.org/W2798701005,All-optical machine learning using diffractive...,machine learning
...,...,...,...
1176,https://openalex.org/W4408802928,Applications of natural language processing an...,large language models
530,https://openalex.org/W4409190866,Benchmarking large language models for biomedi...,natural language processing
1133,https://openalex.org/W4409190866,Benchmarking large language models for biomedi...,large language models
922,https://openalex.org/W4412037398,A Comprehensive Review of Explainable Artifici...,computer vision
1613,https://openalex.org/W4412037398,A Comprehensive Review of Explainable Artifici...,explainable artificial intelligence

In [55]:
clean_papers = (
    combined_papers
    .groupby("id", as_index=False)
    .agg({
        "title": "first",
        "publication_year": "first",
        "type": "first",
        "abstract_inverted_index": "first",
        "cited_by_count": "first",
        "doi": "first",
        "search_area": lambda x: "; ".join(sorted(set(x)))
    })
)

print(clean_papers.shape)

(1713, 8)

In [56]:
clean_papers.columns.tolist()

['id',
 'title',
 'publication_year',
 'type',
 'abstract_inverted_index',
 'cited_by_count',
 'doi',
 'search_area']

In [57]:
clean_papers.iloc[0]["abstract_inverted_index"]

{'This': [0, 29],
 'report': [1, 129],
 'presents': [2],
 'a': [3, 23, 105],
 'detailed': [4],
 'analysis': [5, 43, 126],
 'and': [6, 13, 21, 41, 65, 80, 100, 117],
 'review': [7],
 'of': [8, 32, 38, 70, 94, 97],
 'NLP': [9, 26, 83, 109],
 'evaluation,': [10, 110],
 'in': [11, 14, 34, 48, 62, 88],
 'principle': [12],
 'practice.': [15],
 'Part': [16, 51, 102],
 '1': [17],
 'examines': [18],
 'evaluation': [19, 47, 55, 78, 118],
 'concepts': [20],
 'establishes': [22],
 'framework': [24],
 'for': [25, 60, 82, 115],
 'system': [27, 72, 98],
 'evaluation.': [28, 73],
 'makes': [30],
 'use': [31],
 'experience': [33],
 'the': [35, 42, 67, 95, 128],
 'related': [36],
 'area': [37],
 'information': [39],
 'retrieval': [40],
 'also': [44],
 'refers': [45],
 'to': [46, 90, 108],
 'speech': [49],
 'processing.': [50],
 '2': [52],
 'surveys': [53],
 'significant': [54],
 'work': [56],
 'done': [57],
 'so': [58],
 'far,': [59],
 'instance': [61],
 'machine': [63],
 'translation,': [64],
 'discusses': [66],
 'particular': [68, 89],
 'problems': [69],
 'generic': [71],
 'The': [74, 125],
 'conclusion': [75],
 'is': [76, 130],
 'that': [77],
 'strategies': [79, 114],
 'techniques': [81],
 'need': [84],
 'much': [85],
 'more': [86],
 'development,': [87],
 'take': [91],
 'proper': [92],
 'account': [93],
 'influence': [96],
 'tasks': [99],
 'settings.': [101],
 '3': [103],
 'develops': [104],
 'general': [106],
 'approach': [107],
 'aimed': [111],
 'at': [112],
 'methodologically-sound': [113],
 'test': [116],
 'motivated': [119],
 'by': [120, 132],
 'comprehensive': [121],
 'performance': [122],
 'factor': [123],
 'identification.': [124],
 'throughout': [127],
 'supported': [131],
 'extensive': [133],
 'illustrative': [134],
 'examples.': [135]}

In [58]:
def reconstruct_abstract(inverted_index):
    if not inverted_index:
        return None

    words = []

    for word, positions in inverted_index.items():
        for position in positions:
            words.append((position, word))

    words.sort(key=lambda x: x[0])

    return " ".join(word for position, word in words)

In [59]:
test_abstract = reconstruct_abstract(
    clean_papers.iloc[0]["abstract_inverted_index"]
)

print(test_abstract)

This report presents a detailed analysis and review of NLP evaluation, in principle and in practice. Part 1 examines evaluation concepts and establishes a framework for NLP system evaluation. This makes use of experience in the related area of information retrieval and the analysis also refers to evaluation in speech processing. Part 2 surveys significant evaluation work done so far, for instance in machine translation, and discusses the particular problems of generic system evaluation. The conclusion is that evaluation strategies and techniques for NLP need much more development, in particular to take proper account of the influence of system tasks and settings. Part 3 develops a general approach to NLP evaluation, aimed at methodologically-sound strategies for test and evaluation motivated by comprehensive performance factor identification. The analysis throughout the report is supported by extensive illustrative examples.

In [60]:
clean_papers["abstract"] = clean_papers[
    "abstract_inverted_index"
].apply(reconstruct_abstract)

In [62]:
clean_papers["abstract"].notna().sum()

np.int64(1713)

In [63]:
clean_papers["abstract_word_count"] = (
    clean_papers["abstract"]
    .str.split()
    .str.len()
)

clean_papers["abstract_word_count"].describe()

count    1713.000000
mean      194.931699
std        79.269515
min         1.000000
25%       149.000000
50%       189.000000
75%       235.000000
max      1617.000000
Name: abstract_word_count, dtype: float64

In [64]:
clean_papers[
    clean_papers["abstract_word_count"] <= 10
][[
    "title",
    "abstract",
    "abstract_word_count"
]]

,title,abstract,abstract_word_count
2,Implementation of automatic focusing algorithm...,Robotics Institute,2
21,Reinforcement learning in a large-scale photon...,International audience,2
266,Adversarial attacks on medical machine learning,Emerging vulnerabilities demand new conversations,5
307,Does computer vision matter for action?,Controlled experiments indicate that explicit ...,9
472,Techniques for interpretable machine learning,Uncovering the mysterious ways machine learnin...,9
1416,AudioMNIST: Exploring Explainable Artificial I...,418,1

In [65]:
clean_papers = clean_papers[
    clean_papers["abstract_word_count"] >= 20
].copy()

print(clean_papers.shape)

(1700, 10)

In [66]:
clean_papers["abstract_word_count"].describe()

count    1700.000000
mean      196.333529
std        77.924783
min        20.000000
25%       149.000000
50%       189.000000
75%       235.000000
max      1617.000000
Name: abstract_word_count, dtype: float64

In [67]:
import os
print(os.getcwd())

c:\deeksha\scientific-literature-research-assistant\notebooks

In [68]:
clean_papers.to_csv(
    "../data/processed/papers_clean.csv",
    index=False
)

In [69]:
import os

print(os.path.exists("../data/processed/papers_clean.csv"))

True

In [71]:
from sentence_transformers import SentenceTransformer

In [72]:
model = SentenceTransformer("all-MiniLM-L6-v2")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

c:\deeksha\scientific-literature-research-assistant\.venv\lib\site-packages\huggingface_hub\file_download.py:141: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\LENOVO\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
sample_abstracts = clean_papers["abstract"].head(5).tolist()

embeddings = model.encode(
    sample_abstracts,
    show_progress_bar=False
)

print(embeddings.shape)

In [ ]:
print(type(model))

In [ ]:
print("HELLO")

In [1]:
import pandas as pd
import numpy as np

clean_papers = pd.read_csv(
    "../data/processed/papers_clean.csv"
)

print(clean_papers.shape)

(1700, 10)

In [2]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

print("MODEL LOADED")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

MODEL LOADED

In [3]:
test_embedding = model.encode(
    [clean_papers["abstract"].iloc[0]],
    show_progress_bar=False
)

print(test_embedding.shape)

(1, 384)

In [4]:
abstracts = clean_papers["abstract"].tolist()

paper_embeddings = model.encode(
    abstracts,
    batch_size=32,
    show_progress_bar=True
)

print(paper_embeddings.shape)

Batches:   0%|          | 0/54 [00:00<?, ?it/s]

(1700, 384)

In [5]:
np.save(
    "../data/processed/paper_embeddings.npy",
    paper_embeddings
)

print("Embeddings saved!")

Embeddings saved!

In [6]:
import os

print(
    os.path.exists(
        "../data/processed/paper_embeddings.npy"
    )
)

True

In [7]:
paper_embeddings = np.load(
    "../data/processed/paper_embeddings.npy"
)

print(paper_embeddings.shape)

(1700, 384)

In [8]:
from sklearn.metrics.pairwise import cosine_similarity

similarity_matrix = cosine_similarity(paper_embeddings)

print(similarity_matrix.shape)

(1700, 1700)

In [9]:
def find_similar_papers(paper_index, top_n=10):
    
    similarities = similarity_matrix[paper_index]
    
    similar_indices = np.argsort(similarities)[::-1]
    
    similar_indices = similar_indices[similar_indices != paper_index]
    
    top_indices = similar_indices[:top_n]
    
    results = clean_papers.iloc[top_indices][
        ["title", "publication_year", "cited_by_count"]
    ].copy()
    
    results["similarity"] = similarities[top_indices]
    
    return results

In [10]:
find_similar_papers(0)

,title,publication_year,cited_by_count,similarity
1431,A Survey on Evaluation of Large Language Models,2024,2726,0.606805
931,Assessing the Performance of Clinical Natural ...,2021,68,0.600163
1667,BERT applications in natural language processi...,2025,224,0.571464
94,Clinical Natural Language Processing in langua...,2018,313,0.564041
884,Adapting natural language processing for techn...,2021,62,0.554487
1647,Natural Language Processing for Dialects of a ...,2025,44,0.551852
840,State of Art for Semantic Analysis of Natural ...,2021,80,0.550558
1078,State of Art for Semantic Analysis of Natural ...,2021,108,0.550558
567,Natural language processing (NLP) in managemen...,2020,536,0.550060
1621,Advancements in natural language processing: I...,2024,109,0.549666

In [11]:
clean_papers[clean_papers["title"].duplicated(keep=False)][
    ["id", "title", "publication_year"]
].sort_values("title").head(30)

,id,title,publication_year
1019,https://openalex.org/W4206205659,COVID-19 Control by Computer Vision Approaches...,2020
677,https://openalex.org/W3091248836,COVID-19 Control by Computer Vision Approaches...,2020
61,https://openalex.org/W2794284562,Deep Learning for Computer Vision: A Brief Review,2018
1047,https://openalex.org/W4220679327,Deep Learning for Computer Vision: A Brief Review,2022
1072,https://openalex.org/W4226178750,Explainability and artificial intelligence in ...,2022
1055,https://openalex.org/W4221067291,Explainability and artificial intelligence in ...,2022
1092,https://openalex.org/W4283268983,Explainable Artificial Intelligence (XAI),2022
1404,https://openalex.org/W4389510386,Explainable Artificial Intelligence (XAI),2023
1408,https://openalex.org/W4389739628,Explainable Artificial Intelligence (XAI),2023
715,https://openalex.org/W3099487920,Flood Prediction Using Machine Learning Models...,2018
173,https://openalex.org/W2899023746,Flood Prediction Using Machine Learning Models...,2018
720,https://openalex.org/W3101867861,Pulling out all the tops with computer vision ...,2022
53,https://openalex.org/W2792435888,Pulling out all the tops with computer vision ...,2018
1078,https://openalex.org/W4251745552,State of Art for Semantic Analysis of Natural ...,2021
840,https://openalex.org/W3146248749,State of Art for Semantic Analysis of Natural ...,2021
332,https://openalex.org/W2962700793,Threat of Adversarial Attacks on Deep Learning...,2018
27,https://openalex.org/W2782217514,Threat of Adversarial Attacks on Deep Learning...,2018
1190,https://openalex.org/W4312921962,Towards Industrial Revolution 5.0 and Explaina...,2022
1263,https://openalex.org/W4364858182,Towards Industrial Revolution 5.0 and Explaina...,2022

In [12]:
clean_papers["title"].nunique()

1690

In [13]:
duplicate_titles = clean_papers[
    clean_papers["title"].duplicated(keep=False)
].sort_values("title")

duplicate_titles[
    ["id", "title", "publication_year", "doi"]
]

,id,title,publication_year,doi
1019,https://openalex.org/W4206205659,COVID-19 Control by Computer Vision Approaches...,2020,https://doi.org/10.3929/ethz-b-000446917
677,https://openalex.org/W3091248836,COVID-19 Control by Computer Vision Approaches...,2020,https://doi.org/10.1109/access.2020.3027685
61,https://openalex.org/W2794284562,Deep Learning for Computer Vision: A Brief Review,2018,https://doi.org/10.1155/2018/7068349
1047,https://openalex.org/W4220679327,Deep Learning for Computer Vision: A Brief Review,2022,https://doi.org/10.48175/ijarsct-2898
1072,https://openalex.org/W4226178750,Explainability and artificial intelligence in ...,2022,NaN
1055,https://openalex.org/W4221067291,Explainability and artificial intelligence in ...,2022,https://doi.org/10.1016/s2589-7500(22)00029-2
1092,https://openalex.org/W4283268983,Explainable Artificial Intelligence (XAI),2022,https://doi.org/10.6017/ital.v41i2.14683
1404,https://openalex.org/W4389510386,Explainable Artificial Intelligence (XAI),2023,https://doi.org/10.48047/ijfans/v12/i1/271
1408,https://openalex.org/W4389739628,Explainable Artificial Intelligence (XAI),2023,https://doi.org/10.36893/jnao.2022.v13i02.041-047
715,https://openalex.org/W3099487920,Flood Prediction Using Machine Learning Models...,2018,NaN
173,https://openalex.org/W2899023746,Flood Prediction Using Machine Learning Models...,2018,https://doi.org/10.3390/w10111536
720,https://openalex.org/W3101867861,Pulling out all the tops with computer vision ...,2022,https://doi.org/10.1007/jhep10%282018%29121
53,https://openalex.org/W2792435888,Pulling out all the tops with computer vision ...,2018,https://doi.org/10.1007/jhep10(2018)121
1078,https://openalex.org/W4251745552,State of Art for Semantic Analysis of Natural ...,2021,https://doi.org/10.48161/qaj.v1n2a40
840,https://openalex.org/W3146248749,State of Art for Semantic Analysis of Natural ...,2021,https://doi.org/10.48161/qaj.v1n2a44
332,https://openalex.org/W2962700793,Threat of Adversarial Attacks on Deep Learning...,2018,https://doi.org/10.1109/access.2018.2807385
27,https://openalex.org/W2782217514,Threat of Adversarial Attacks on Deep Learning...,2018,https://doi.org/10.48550/arxiv.1801.00553
1190,https://openalex.org/W4312921962,Towards Industrial Revolution 5.0 and Explaina...,2022,https://doi.org/10.12785/ijcds/120128
1263,https://openalex.org/W4364858182,Towards Industrial Revolution 5.0 and Explaina...,2022,https://doi.org/10.12785/ijcds/120124

In [14]:
print("Total papers:", len(clean_papers))
print("Unique titles:", clean_papers["title"].nunique())
print("Duplicate title records:", 
      clean_papers["title"].duplicated().sum())

Total papers: 1700
Unique titles: 1690
Duplicate title records: 10

In [15]:
clean_papers["doi_clean"] = (
    clean_papers["doi"]
    .fillna("")
    .str.lower()
    .str.strip()
    .str.replace("https://doi.org/", "", regex=False)
    .str.replace("http://doi.org/", "", regex=False)
)

In [16]:
doi_duplicates = clean_papers[
    (clean_papers["doi_clean"] != "") &
    (clean_papers["doi_clean"].duplicated(keep=False))
].sort_values("doi_clean")

doi_duplicates[
    ["id", "title", "publication_year", "doi_clean"]
]

Empty DataFrame
Columns: [id, title, publication_year, doi_clean]
Index: []

In [17]:
print(
    "Duplicate DOI records:",
    clean_papers[
        (clean_papers["doi_clean"] != "")
    ]["doi_clean"].duplicated().sum()
)

Duplicate DOI records: 0

In [18]:
print(paper_embeddings.shape)
print(similarity_matrix.shape)

(1700, 384)
(1700, 1700)

In [19]:
test_indices = [0, 100, 500, 1000, 1500]

for idx in test_indices:
    print("\n" + "="*80)
    print("QUERY:", clean_papers.iloc[idx]["title"])
    print("="*80)
    
    results = find_similar_papers(idx, top_n=5)
    
    for i, row in results.iterrows():
        print(f"- {row['title']}")
        print(f"  Similarity: {row['similarity']:.3f}")

================================================================================
QUERY: Evaluating natural language processing systems
================================================================================
- A Survey on Evaluation of Large Language Models
  Similarity: 0.607
- Assessing the Performance of Clinical Natural Language Processing Systems: Development of an Evaluation Methodology
  Similarity: 0.600
- BERT applications in natural language processing: a review
  Similarity: 0.571
- Clinical Natural Language Processing in languages other than English: opportunities and challenges
  Similarity: 0.564
- Adapting natural language processing for technical text
  Similarity: 0.554

================================================================================
QUERY: Deep Learning for Intelligent Wireless Networks: A Comprehensive Survey
================================================================================
- Deep Learning in Mobile and Wireless Networking: A Survey
  Similarity: 0.658
- Modulation Classification Based on Signal Constellation Diagrams and Deep Learning
  Similarity: 0.635
- Artificial Neural Networks-Based Machine Learning for Wireless Networks: A Tutorial
  Similarity: 0.627
- A comprehensive survey on machine learning for networking: evolution, applications and research opportunities
  Similarity: 0.621
- A Survey of Machine Learning Techniques Applied to Software Defined Networking (SDN): Research Issues and Challenges
  Similarity: 0.610

================================================================================
QUERY: Fastai: A Layered API for Deep Learning
================================================================================
- TVM: an automated end-to-end optimizing compiler for deep learning
  Similarity: 0.663
- Machine Learning and Deep Learning frameworks and libraries for large-scale data mining: a survey
  Similarity: 0.640
- Deep learning with Python
  Similarity: 0.633
- Deep Learning With TensorFlow: A Review
  Similarity: 0.629
- Tensor Methods in Computer Vision and Deep Learning
  Similarity: 0.619

================================================================================
QUERY: Reinforcement Learning in Healthcare: A Survey
================================================================================
- Reinforcement Learning for Clinical Decision Support in Critical Care: Comprehensive Review
  Similarity: 0.717
- An Introduction to Deep Reinforcement Learning
  Similarity: 0.655
- Explainable Reinforcement Learning: A Survey and Comparative Review
  Similarity: 0.643
- Deep reinforcement learning: a survey
  Similarity: 0.637
- A Survey on Offline Reinforcement Learning: Taxonomy, Review, and Open Problems
  Similarity: 0.626

================================================================================
QUERY: TRIPOD+AI statement: updated guidance for reporting clinical prediction models that use regression or machine learning methods
================================================================================
- Explainable artificial intelligence models using real-world electronic health record data: a systematic scoping review
  Similarity: 0.672
- Leveraging explainable artificial intelligence to optimize clinical decision support
  Similarity: 0.632
- Explainable artificial intelligence model to predict acute critical illness from electronic health records
  Similarity: 0.623
- Explainable Artificial Intelligence Model for Stroke Prediction Using EEG Signal
  Similarity: 0.576
- Machine-Learning-Based Disease Diagnosis: A Comprehensive Review
  Similarity: 0.576

In [20]:
clean_papers["retrieval_text"] = (
    clean_papers["title"].fillna("") 
    + ". "
    + clean_papers["abstract"].fillna("")
)

clean_papers["retrieval_text"].head(3)

0    Evaluating natural language processing systems...
1    Maximum Entropy Inverse Reinforcement Learning...
2    Natural Language Processing. International Jou...
Name: retrieval_text, dtype: object

In [21]:
clean_papers["retrieval_text"].str.len().describe()

count     1700.000000
mean      1466.374706
std        554.372763
min        169.000000
25%       1141.250000
50%       1409.500000
75%       1736.250000
max      11521.000000
Name: retrieval_text, dtype: float64

In [22]:
title_abstract_embeddings = model.encode(
    clean_papers["retrieval_text"].tolist(),
    show_progress_bar=True,
    batch_size=32
)

print(title_abstract_embeddings.shape)

Batches:   0%|          | 0/54 [00:00<?, ?it/s]

(1700, 384)

In [23]:
from sklearn.metrics.pairwise import cosine_similarity

improved_similarity = cosine_similarity(title_abstract_embeddings)

print(improved_similarity.shape)

(1700, 1700)

In [24]:
query = "Evaluating natural language processing systems"

query_embedding = model.encode([query])

scores = cosine_similarity(
    query_embedding,
    title_abstract_embeddings
)[0]

top_indices = scores.argsort()[::-1][:10]

results = clean_papers.iloc[top_indices][
    ["title", "publication_year", "cited_by_count"]
].copy()

results["similarity"] = scores[top_indices]

results

,title,publication_year,cited_by_count,similarity
0,Evaluating natural language processing systems,2021,134,0.779878
931,Assessing the Performance of Clinical Natural ...,2021,68,0.651581
412,An Overview of Natural Language Processing,2019,37,0.614780
1431,A Survey on Evaluation of Large Language Models,2024,2726,0.607130
1078,State of Art for Semantic Analysis of Natural ...,2021,108,0.600091
840,State of Art for Semantic Analysis of Natural ...,2021,80,0.600091
884,Adapting natural language processing for techn...,2021,62,0.560329
1323,Efficient Methods for Natural Language Process...,2023,98,0.559287
567,Natural language processing (NLP) in managemen...,2020,536,0.553930
1621,Advancements in natural language processing: I...,2024,109,0.551392

In [25]:
print("Current records:", len(clean_papers))
print("Current unique papers:", clean_papers["id"].nunique())
print("Search areas:", clean_papers["search_area"].nunique())

Current records: 1700
Current unique papers: 1700
Search areas: 15

In [26]:
clean_papers["search_area"].value_counts()

search_area
reinforcement learning                                   246
explainable artificial intelligence                      245
large language models                                    243
natural language processing                              240
computer vision                                          240
machine learning                                         229
deep learning                                            220
deep learning; machine learning                           16
computer vision; deep learning                             7
large language models; natural language processing         6
deep learning; reinforcement learning                      3
deep learning; natural language processing                 2
explainable artificial intelligence; machine learning      1
deep learning; explainable artificial intelligence         1
computer vision; explainable artificial intelligence       1
Name: count, dtype: int64

In [30]:
print("Number of completed areas:", len(all_papers))

for i, df in enumerate(all_papers):
    print(i, research_areas[i], len(df))

Number of completed areas: 4
0 machine learning 1500
1 deep learning 1500
2 natural language processing 1500
3 computer vision 1500